# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

table:
-
  title: Blog
  path: /
  type: sitelink
-
  title: Github
  path: https://github.com/PengjieChen
  type: permalink
-
  title: CV
  path: /CV
  type: sitelink
-
  title: 404
  path: /non-exist
  type: sitelink

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
# With extra Author info
aboutAU: 'Location in hz, want to be a web frontend developer'
